require 'bundler/setup'
require 'fake_project_dependency'

puts FakeProjectDependency.hello
puts FakeProjectDependency.a_wild_method_appeared
puts FakeProjectDependency.nathans_method
puts FakeProjectDependency.test_method
puts FakeProjectDependency.sup_dawg
